{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name:
    {{ printf "%s-selfsigned" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  selfSigned: {}
  {{- end }}