{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-envoy" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  secretName: {{ printf "%s-envoy-crt" (include "common.names.fullname" .) }}
  commonName: "envoy"
  dnsNames:
    - {{ printf "%s-envoy" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" | quote}}
    - "{{ printf "%s-envoy" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}.{{ include "common.names.namespace" . }}"
    - "{{ printf "%s-envoy" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}.{{ include "common.names.namespace" . }}.svc"
    - "{{ printf "%s-envoy" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}.{{ include "common.names.namespace" . }}.svc.cluster.local"
  issuerRef:
    name: {{ include "common.names.fullname" . | quote }}
    kind: Issuer
{{- end }}
